version: '3'
services:
  master:
    build: ./jenkins
    image: jenkins-docker-master
    container_name: jenkins_devops
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
  nginx:
    build: ./nginx
    image: nginx-docker-master
    container_name: nginx_devops
    ports:
      - "80:80"
    networks:
      - jenkins-net
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:
